version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestIsthmusDB;User=sa;Password=YourStrong!Password;Encrypt=False;TrustServerCertificate=True
    volumes:
      - C:/Users/diego/.nuget/packages:/root/.nuget/packages:ro
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data: